export const DEFAULT_BROWSER_TIMEOUT_MS = 30_000
export const MAX_BROWSER_TIMEOUT_MS = 120_000
export const MAX_PAGE_SIZE_BYTES = 100 * 1024 * 1024
export const DEFAULT_BROWSER_RETRIES = 2
export const DEFAULT_BROWSER_RETRY_DELAY_MS = 250
export const DEFAULT_MAX_REDIRECTS = 10
export const DEFAULT_BROWSER_USER_AGENT = 'VexloBrowser/1.0 (+https://vexlo.app)'
export const DEFAULT_ACCEPT_LANGUAGE = 'en-US,en;q=0.9'
export const DEFAULT_COMPRESSION = true
export const NATIVE_FETCH_PROVIDER_ID = 'native-fetch'
export const DEFAULT_CHUNK_SIZE = 4000
export const DEFAULT_CHUNK_OVERLAP = 400
export const BROWSER_CACHE_TTL_MS = 60 * 60 * 1000
export const MAX_CONCURRENT_BROWSER_REQUESTS = 3
export const SUPPORTED_CONTENT_TYPES = ['text/html', 'application/xhtml+xml', 'text/plain'] as const
export const BROWSER_ID_PREFIX = 'browser_'
export const CONTENT_HASH_ALGORITHM = 'sha256'
export const MIN_CONTENT_LENGTH = 100
export const READABILITY_THRESHOLD = 0.3
export const MAX_CHUNKS_PER_DOCUMENT = 100
export const DEFAULT_LANGUAGE = 'en'
export const HEALTH_CHECK_INTERVAL_MS = 60_000
