/**
 * Planner Agent Types
 *
 * Defines all TypeScript models and interfaces for the Planner Agent.
 * Planner receives a user request and produces a structured execution plan.
 */

import type { SearchQuery } from '@/lib/agents/search/types'

/**
 * Reasoning strategy for plan execution
 */
export enum ReasoningStrategy {
  /** Linear task execution in order */
  LINEAR = 'linear',
  /** Parallel execution where possible */
  PARALLEL = 'parallel',
  /** Tree-based branching for alternatives */
  TREE = 'tree',
  /** Adaptive based on task dependencies */
  ADAPTIVE = 'adaptive',
}

/**
 * Task priority level
 */
export enum TaskPriority {
  CRITICAL = 'critical',
  HIGH = 'high',
  NORMAL = 'normal',
  LOW = 'low',
}

/**
 * Task type classification
 */
export enum TaskType {
  SEARCH = 'search',
  RETRIEVE = 'retrieve',
  REASON = 'reason',
  SYNTHESIZE = 'synthesize',
  CRITIQUE = 'critique',
  VERIFY = 'verify',
  FORMAT = 'format',
}

/**
 * Intent classification from user query
 */
export enum IntentType {
  /** User wants factual information */
  INFORMATIONAL = 'informational',
  /** User wants to understand \"why\" */
  EXPLANATORY = 'explanatory',
  /** User wants analysis and comparison */
  ANALYTICAL = 'analytical',
  /** User wants step-by-step guidance */
  INSTRUCTIONAL = 'instructional',
  /** User wants creativity and ideation */
  CREATIVE = 'creative',
  /** User wants decision support */
  DECISION_SUPPORT = 'decision_support',
}

/**
 * Confidence level for plan quality
 */
export type ConfidenceScore = number & { readonly __confidenceScore: unique symbol }

export function createConfidenceScore(value: number): ConfidenceScore {
  const normalized = Math.max(0, Math.min(1, value))
  return normalized as ConfidenceScore
}

/**
 * Single execution task within a plan
 */
export interface PlanTask {
  /** Unique task identifier */
  id: string
  /** Task type */
  type: TaskType
  /** Human-readable description */
  description: string
  /** Task priority */
  priority: TaskPriority
  /** IDs of tasks that must complete before this one */
  dependsOn: string[]
  /** Expected output description */
  expectedOutput: string
  /** Estimated tokens required for this task */
  estimatedTokens?: number
}

/**
 * Search query generated by planner
 */
export interface GeneratedSearchQuery {
  /** Unique query identifier */
  id: string
  /** The search query itself */
  query: SearchQuery
  /** Why this query is needed */
  rationale: string
  /** Task ID this query supports */
  supportsTask: string
  /** Priority of this search */
  priority: TaskPriority
}

/**
 * Tools required to execute the plan
 */
export interface RequiredTools {
  /** Search providers needed */
  searchProviders: string[]
  /** Browser/retrieval needed */
  browserNeeded: boolean
  /** Reasoning models needed */
  reasoningNeeded: boolean
  /** Critique/verification needed */
  critiqueNeeded: boolean
}

/**
 * Complete execution plan produced by Planner
 */
export interface ExecutionPlan {
  /** Unique plan identifier */
  id: string
  /** Original user query */
  query: string
  /** Detected user intent */
  intent: IntentType
  /** Plan objective */
  objective: string
  /** Detailed execution tasks */
  tasks: PlanTask[]
  /** Search queries to execute */
  searchQueries: GeneratedSearchQuery[]
  /** Tools required for execution */
  requiredTools: RequiredTools
  /** Expected output descriptions */
  expectedOutputs: string[]
  /** Reasoning strategy to use */
  reasoningStrategy: ReasoningStrategy
  /** Overall confidence in this plan (0-1) */
  confidence: ConfidenceScore
  /** Reasoning for the plan */
  reasoning: string
  /** Estimated total tokens needed */
  estimatedTotalTokens: number
  /** Plan created timestamp */
  createdAt: Date
}

/**
 * Input to the Planner
 */
export interface PlannerInput {
  /** User's natural language query */
  query: string
  /** User ID for personalization (optional) */
  userId?: string
  /** Organization ID (optional) */
  organizationId?: string
  /** Maximum tokens to estimate for (optional) */
  maxTokens?: number
}

/**
 * Validation result for a plan
 */
export interface ValidationResult {
  /** Whether plan is valid */
  valid: boolean
  /** List of validation errors if any */
  errors: ValidationError[]
  /** Warnings about the plan */
  warnings: string[]
}

/**
 * Single validation error
 */
export interface ValidationError {
  /** Error code */
  code: string
  /** Human-readable message */
  message: string
  /** Field that failed validation */
  field?: string
}

/**
 * Query analysis result
 */
export interface QueryAnalysis {
  /** Detected intent */
  intent: IntentType
  /** Main topic/entity */
  mainTopic: string
  /** Key entities mentioned */
  entities: string[]
  /** Key concepts */
  concepts: string[]
  /** Complexity level (1-5) */
  complexity: number
  /** Whether query is clear and actionable */
  isActionable: boolean
}
